#!/bin/sh
# Install a global `anywifi` command that runs this repo from any directory.
# Usage:  sudo ./install.sh        (uninstall: sudo rm /usr/local/bin/anywifi)
set -e

REPO="$(cd "$(dirname "$0")" && pwd)"
DEST="/usr/local/bin/anywifi"

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run with sudo:  sudo ./install.sh"
    exit 1
fi

cat > "$DEST" <<EOF
#!/bin/sh
# AnyWifi launcher — generated by install.sh
exec env PYTHONPATH="$REPO" python3 -m anywifi "\$@"
EOF
chmod +x "$DEST"

echo "Installed: $DEST"
echo "Now run 'sudo anywifi' from anywhere."
